### ISSUE TITLE
Transaction history on main screen

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#123]
Show recent transactions for any of configured addresses. In/Out transactions, by filtering all new blocks provided by Geth

**Comment by splix** [comment]
![history](https://user-images.githubusercontent.com/48364/27111753-4528fa1a-5080-11e7-8806-9a92d9d68b79.png)

without search functionality for now

**Comment by whilei** [comment]
Currently `trackedTransactions` are limited to per-session since they're stored only in the `store`. Have ways to persist such data been considered already? 

`localStorage` might be a simple option, although I'm not sure off the top of my head about Electron compatibility. 

Ideally I think it would be better eventually to leave persisting tx history to the connector side, but it wouldn't be too hard to drop in to the app for now.

**Comment by dulanov** [comment]
Our plan was to search transaction from geth last `X` blocks, not store them locally.

**Comment by dulanov** [comment]
https://ethereum.stackexchange.com/questions/2531/common-useful-javascript-snippets-for-geth/3478#3478

**Comment by whilei** [comment]
Where `X` is? 100? 1000? _infinity_?

**Comment by whilei** [comment]
It seems like a very bulky call(s) to make for each session. Is it a security reason for not persisting tx hashes locally?

**Comment by dulanov** [comment]
No, I think, just first dirty impl.

**Comment by splix** [comment]
let's start with per-session history. later (another release) we can add scan and localStorage

**Comment by whilei** [comment]
Ok. So this Issue and it's brother #124 are primarily UI/CSS oriented?

**Comment by splix** [comment]
yes, just basic implementation

**Comment by whilei** [comment]
Resolved in #145. Still TODO: UI style.
