### ISSUE TITLE
Can not send transaction. 

### ISSUE THREAD

**Issue by ChuckSRQ** [ethereumproject/emerald-wallet#213]
Transactions will not send in latest windows build.

**Comment by whilei** [comment]
Are you seeing something like #180?

**Comment by ChuckSRQ** [comment]
No. Nothing happens at all. @whilei

**Comment by elaineo** [comment]
looks like a bug in the validation process. i'll look at this today

**Comment by elaineo** [comment]
@ChuckSRQ on startup, did you select mewapi as your node?  mewapi is running parity, so `eth_traceCall` does not work. 

I am going to disable trace for the current send transaction as a short term fix, because it does not make sense to require a trace for send validation. Longer term, the launcher should do a `web3_clientVersion` rpc call.
