### ISSUE TITLE
The currency was not sent to my wallet

### ISSUE THREAD

**Issue by ysamir48** [ethereumproject/emerald-wallet#488]
Hi my friend
I have a problem I have sent to the portfolio of the site so far has not reached Lia Shi and this address of the transmitter

0x5a10b5e4eb7a0ba32d1788ba30a86b8f04ba79125824e9b49f6fc3eee1c5957d

![2018-02-16_204232](https://user-images.githubusercontent.com/36533810/36321210-1b290fdc-135a-11e8-9707-e88391f30432.png)

This is the title of the wallet that has been sent to her and nothing has come of it so far
0x3af801bce9cbb60fbf0375a55117a053d0002843
![2018-02-16_204329](https://user-images.githubusercontent.com/36533810/36321253-3fe0f24a-135a-11e8-97a5-6b20e5a9b16b.png)

**Comment by splix** [comment]
Your client is currently on block #969k of total #5400k. Before your client will be synchronized you'll see wrong balance, because you don't have full information. It may take several days to download and process whole blockchain state.

As an option you can switch to a remote node (epool or gastracker mainnet)
